# Generated by Django 3.0.2 on 2020-01-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('channel_id', models.CharField(max_length=256)),
                ('channel_url', models.CharField(max_length=1024)),
                ('logo', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Cursor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.CharField(max_length=256)),
                ('finished', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.CharField(max_length=1024)),
                ('channel_name', models.CharField(max_length=256)),
                ('channel_logo', models.CharField(max_length=2048)),
                ('tracking_id', models.CharField(max_length=256)),
                ('vod_id', models.CharField(max_length=256)),
                ('vod_url', models.CharField(max_length=2048)),
                ('vod_offset', models.IntegerField()),
                ('vod_preview_img', models.CharField(max_length=2048)),
                ('game', models.CharField(max_length=2048)),
                ('views', models.IntegerField()),
                ('duration', models.FloatField()),
                ('created_at', models.TimeField()),
                ('medium_thumbnail', models.CharField(max_length=2048)),
                ('small_thumbnail', models.CharField(max_length=2048)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Channel')),
            ],
        ),
    ]
