# Generated by Django 3.0.2 on 2020-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200105_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
