# Generated by Django 3.0.1 on 2020-01-06 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200105_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=2048)),
                ('filename', models.CharField(max_length=2048)),
                ('path', models.CharField(max_length=2048)),
                ('start_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('upload_complete', models.BooleanField(default=True)),
                ('encode_complete', models.BooleanField(default=False)),
                ('file_deleted', models.BooleanField(default=False)),
                ('clip_type', models.SmallIntegerField(default=0)),
                ('clip_used', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlightclip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
