# Generated by Django 3.0.2 on 2020-01-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_highlightclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='download_url',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
