# Generated by Django 3.0.2 on 2020-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_clip_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='downloaded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
